-- Maak een nieuwe tabel die de totaaltellingen bijhoudt met drie kolommen: telling_id,
-- telling_omschrijving en telling_getal. Voeg een regel toe met als telling_omschrijving
-- ‘totale salariskosten’ en als telling_getal het totaal van de salariskosten.
-- Schrijf vervolgens een stored procedure die de totale salariskosten update met een
-- bepaald bedrag in de totaaltellingen tabel. Schrijf vervolgens een trigger die wanneer
-- een nieuw personeelslid wordt toegevoegd met salaris automatisch de totale salariskosten
-- update in de totaaltellingen tabel.